### ISSUE TITLE
可能是版本不兼容的错误

### ISSUE THREAD

**Issue by JiangQiYan713** [SlimefunGuguProject/SfChunkInfo#4]
报错内容
```
[20:16:36 INFO]: JiangQiYan issued server command: /sfchunkinfo JiangQiYan
[20:16:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sfchunkinfo' in plugin SfChunkInfo vBuild 6 zh-CN(ybw0014) (git 5176ff6)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:931) ~[paper-1.19.3.jar:git-Paper-404]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-404]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-404]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/github/thebusybiscuit/slimefun4/utils/WorldUtils
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.scanChunk(ScanChunk.java:104) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.getAmountOthers(ScanChunk.java:91) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.onCommand(ScanChunk.java:61) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: io.github.thebusybiscuit.slimefun4.utils.WorldUtils
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.scanChunk(ScanChunk.java:104) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.getAmountOthers(ScanChunk.java:91) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at me.fnfal113.sfchunkinfo.commands.ScanChunk.onCommand(ScanChunk.java:61) ~[SfChunkInfo-Build 6 zh-CN(ybw0014) (git 5176ff6).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```
![WNAMT$ 9F227@@ZRVKCZ}VA](https://user-images.githubusercontent.com/91627081/219947498-f5edcb54-2e95-45ca-a846-ec29e7538112.png)
![LN`BGGY@380%R6NAO @`FMS](https://user-images.githubusercontent.com/91627081/219947505-39ea07ac-8822-41d1-9e1d-d2d7f5325fef.png)
![A~JM0C7KBPZ))IMB%O~_F@T](https://user-images.githubusercontent.com/91627081/219947509-8a71d9f6-4429-479d-b40b-15f9e3120a29.png)

**Comment by ybw0014** [comment]
确实，那个类已经在新版中移除了
